// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSchedulesSchedulesCreateParams creates a new SchedulesSchedulesCreateParams object
// with the default values initialized.
func NewSchedulesSchedulesCreateParams() *SchedulesSchedulesCreateParams {
	var ()
	return &SchedulesSchedulesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulesSchedulesCreateParamsWithTimeout creates a new SchedulesSchedulesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSchedulesSchedulesCreateParamsWithTimeout(timeout time.Duration) *SchedulesSchedulesCreateParams {
	var ()
	return &SchedulesSchedulesCreateParams{

		timeout: timeout,
	}
}

// NewSchedulesSchedulesCreateParamsWithContext creates a new SchedulesSchedulesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSchedulesSchedulesCreateParamsWithContext(ctx context.Context) *SchedulesSchedulesCreateParams {
	var ()
	return &SchedulesSchedulesCreateParams{

		Context: ctx,
	}
}

// NewSchedulesSchedulesCreateParamsWithHTTPClient creates a new SchedulesSchedulesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSchedulesSchedulesCreateParamsWithHTTPClient(client *http.Client) *SchedulesSchedulesCreateParams {
	var ()
	return &SchedulesSchedulesCreateParams{
		HTTPClient: client,
	}
}

/*SchedulesSchedulesCreateParams contains all the parameters to send to the API endpoint
for the schedules schedules create operation typically these are written to a http.Request
*/
type SchedulesSchedulesCreateParams struct {

	/*Data*/
	Data interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) WithTimeout(timeout time.Duration) *SchedulesSchedulesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) WithContext(ctx context.Context) *SchedulesSchedulesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) WithHTTPClient(client *http.Client) *SchedulesSchedulesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) WithData(data interface{}) *SchedulesSchedulesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the schedules schedules create params
func (o *SchedulesSchedulesCreateParams) SetData(data interface{}) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulesSchedulesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
