// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSchedulesSchedulesCredentialsCreateParams creates a new SchedulesSchedulesCredentialsCreateParams object
// with the default values initialized.
func NewSchedulesSchedulesCredentialsCreateParams() *SchedulesSchedulesCredentialsCreateParams {
	var ()
	return &SchedulesSchedulesCredentialsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulesSchedulesCredentialsCreateParamsWithTimeout creates a new SchedulesSchedulesCredentialsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSchedulesSchedulesCredentialsCreateParamsWithTimeout(timeout time.Duration) *SchedulesSchedulesCredentialsCreateParams {
	var ()
	return &SchedulesSchedulesCredentialsCreateParams{

		timeout: timeout,
	}
}

// NewSchedulesSchedulesCredentialsCreateParamsWithContext creates a new SchedulesSchedulesCredentialsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSchedulesSchedulesCredentialsCreateParamsWithContext(ctx context.Context) *SchedulesSchedulesCredentialsCreateParams {
	var ()
	return &SchedulesSchedulesCredentialsCreateParams{

		Context: ctx,
	}
}

// NewSchedulesSchedulesCredentialsCreateParamsWithHTTPClient creates a new SchedulesSchedulesCredentialsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSchedulesSchedulesCredentialsCreateParamsWithHTTPClient(client *http.Client) *SchedulesSchedulesCredentialsCreateParams {
	var ()
	return &SchedulesSchedulesCredentialsCreateParams{
		HTTPClient: client,
	}
}

/*SchedulesSchedulesCredentialsCreateParams contains all the parameters to send to the API endpoint
for the schedules schedules credentials create operation typically these are written to a http.Request
*/
type SchedulesSchedulesCredentialsCreateParams struct {

	/*Data*/
	Data SchedulesSchedulesCredentialsCreateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) WithTimeout(timeout time.Duration) *SchedulesSchedulesCredentialsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) WithContext(ctx context.Context) *SchedulesSchedulesCredentialsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) WithHTTPClient(client *http.Client) *SchedulesSchedulesCredentialsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) WithData(data SchedulesSchedulesCredentialsCreateBody) *SchedulesSchedulesCredentialsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) SetData(data SchedulesSchedulesCredentialsCreateBody) {
	o.Data = data
}

// WithID adds the id to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) WithID(id string) *SchedulesSchedulesCredentialsCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the schedules schedules credentials create params
func (o *SchedulesSchedulesCredentialsCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulesSchedulesCredentialsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
