// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SchedulesSchedulesJobsListReader is a Reader for the SchedulesSchedulesJobsList structure.
type SchedulesSchedulesJobsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulesSchedulesJobsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulesSchedulesJobsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSchedulesSchedulesJobsListOK creates a SchedulesSchedulesJobsListOK with default headers values
func NewSchedulesSchedulesJobsListOK() *SchedulesSchedulesJobsListOK {
	return &SchedulesSchedulesJobsListOK{}
}

/*SchedulesSchedulesJobsListOK handles this case with default header values.

OK
*/
type SchedulesSchedulesJobsListOK struct {
}

func (o *SchedulesSchedulesJobsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/schedules/{id}/jobs/][%d] schedulesSchedulesJobsListOK ", 200)
}

func (o *SchedulesSchedulesJobsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
