// Code generated by go-swagger; DO NOT EDIT.

package versioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// VersioningListReader is a Reader for the VersioningList structure.
type VersioningListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersioningListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVersioningListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersioningListOK creates a VersioningListOK with default headers values
func NewVersioningListOK() *VersioningListOK {
	return &VersioningListOK{}
}

/*VersioningListOK handles this case with default header values.

OK
*/
type VersioningListOK struct {
}

func (o *VersioningListOK) Error() string {
	return fmt.Sprintf("[GET /api/][%d] versioningListOK ", 200)
}

func (o *VersioningListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
