// Code generated by go-swagger; DO NOT EDIT.

package inventory_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInventorySourcesInventorySourcesUpdateCreateParams creates a new InventorySourcesInventorySourcesUpdateCreateParams object
// with the default values initialized.
func NewInventorySourcesInventorySourcesUpdateCreateParams() *InventorySourcesInventorySourcesUpdateCreateParams {
	var ()
	return &InventorySourcesInventorySourcesUpdateCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInventorySourcesInventorySourcesUpdateCreateParamsWithTimeout creates a new InventorySourcesInventorySourcesUpdateCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInventorySourcesInventorySourcesUpdateCreateParamsWithTimeout(timeout time.Duration) *InventorySourcesInventorySourcesUpdateCreateParams {
	var ()
	return &InventorySourcesInventorySourcesUpdateCreateParams{

		timeout: timeout,
	}
}

// NewInventorySourcesInventorySourcesUpdateCreateParamsWithContext creates a new InventorySourcesInventorySourcesUpdateCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewInventorySourcesInventorySourcesUpdateCreateParamsWithContext(ctx context.Context) *InventorySourcesInventorySourcesUpdateCreateParams {
	var ()
	return &InventorySourcesInventorySourcesUpdateCreateParams{

		Context: ctx,
	}
}

// NewInventorySourcesInventorySourcesUpdateCreateParamsWithHTTPClient creates a new InventorySourcesInventorySourcesUpdateCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInventorySourcesInventorySourcesUpdateCreateParamsWithHTTPClient(client *http.Client) *InventorySourcesInventorySourcesUpdateCreateParams {
	var ()
	return &InventorySourcesInventorySourcesUpdateCreateParams{
		HTTPClient: client,
	}
}

/*InventorySourcesInventorySourcesUpdateCreateParams contains all the parameters to send to the API endpoint
for the inventory sources inventory sources update create operation typically these are written to a http.Request
*/
type InventorySourcesInventorySourcesUpdateCreateParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) WithTimeout(timeout time.Duration) *InventorySourcesInventorySourcesUpdateCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) WithContext(ctx context.Context) *InventorySourcesInventorySourcesUpdateCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) WithHTTPClient(client *http.Client) *InventorySourcesInventorySourcesUpdateCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) WithID(id string) *InventorySourcesInventorySourcesUpdateCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the inventory sources inventory sources update create params
func (o *InventorySourcesInventorySourcesUpdateCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *InventorySourcesInventorySourcesUpdateCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
