// Code generated by go-swagger; DO NOT EDIT.

package inventory_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventorySourcesInventorySourcesHostsListReader is a Reader for the InventorySourcesInventorySourcesHostsList structure.
type InventorySourcesInventorySourcesHostsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventorySourcesInventorySourcesHostsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventorySourcesInventorySourcesHostsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInventorySourcesInventorySourcesHostsListOK creates a InventorySourcesInventorySourcesHostsListOK with default headers values
func NewInventorySourcesInventorySourcesHostsListOK() *InventorySourcesInventorySourcesHostsListOK {
	return &InventorySourcesInventorySourcesHostsListOK{}
}

/*InventorySourcesInventorySourcesHostsListOK handles this case with default header values.

OK
*/
type InventorySourcesInventorySourcesHostsListOK struct {
}

func (o *InventorySourcesInventorySourcesHostsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/inventory_sources/{id}/hosts/][%d] inventorySourcesInventorySourcesHostsListOK ", 200)
}

func (o *InventorySourcesInventorySourcesHostsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
