// Code generated by go-swagger; DO NOT EDIT.

package credential_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialTypesCredentialTypesCreateReader is a Reader for the CredentialTypesCredentialTypesCreate structure.
type CredentialTypesCredentialTypesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialTypesCredentialTypesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCredentialTypesCredentialTypesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCredentialTypesCredentialTypesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCredentialTypesCredentialTypesCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCredentialTypesCredentialTypesCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCredentialTypesCredentialTypesCreateCreated creates a CredentialTypesCredentialTypesCreateCreated with default headers values
func NewCredentialTypesCredentialTypesCreateCreated() *CredentialTypesCredentialTypesCreateCreated {
	return &CredentialTypesCredentialTypesCreateCreated{}
}

/*CredentialTypesCredentialTypesCreateCreated handles this case with default header values.

CredentialTypesCredentialTypesCreateCreated credential types credential types create created
*/
type CredentialTypesCredentialTypesCreateCreated struct {
}

func (o *CredentialTypesCredentialTypesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/][%d] credentialTypesCredentialTypesCreateCreated ", 201)
}

func (o *CredentialTypesCredentialTypesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesCreateBadRequest creates a CredentialTypesCredentialTypesCreateBadRequest with default headers values
func NewCredentialTypesCredentialTypesCreateBadRequest() *CredentialTypesCredentialTypesCreateBadRequest {
	return &CredentialTypesCredentialTypesCreateBadRequest{}
}

/*CredentialTypesCredentialTypesCreateBadRequest handles this case with default header values.

Bad Request
*/
type CredentialTypesCredentialTypesCreateBadRequest struct {
}

func (o *CredentialTypesCredentialTypesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/][%d] credentialTypesCredentialTypesCreateBadRequest ", 400)
}

func (o *CredentialTypesCredentialTypesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesCreateUnauthorized creates a CredentialTypesCredentialTypesCreateUnauthorized with default headers values
func NewCredentialTypesCredentialTypesCreateUnauthorized() *CredentialTypesCredentialTypesCreateUnauthorized {
	return &CredentialTypesCredentialTypesCreateUnauthorized{}
}

/*CredentialTypesCredentialTypesCreateUnauthorized handles this case with default header values.

Unauthorised
*/
type CredentialTypesCredentialTypesCreateUnauthorized struct {
}

func (o *CredentialTypesCredentialTypesCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/][%d] credentialTypesCredentialTypesCreateUnauthorized ", 401)
}

func (o *CredentialTypesCredentialTypesCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialTypesCredentialTypesCreateForbidden creates a CredentialTypesCredentialTypesCreateForbidden with default headers values
func NewCredentialTypesCredentialTypesCreateForbidden() *CredentialTypesCredentialTypesCreateForbidden {
	return &CredentialTypesCredentialTypesCreateForbidden{}
}

/*CredentialTypesCredentialTypesCreateForbidden handles this case with default header values.

No Permission Response
*/
type CredentialTypesCredentialTypesCreateForbidden struct {
}

func (o *CredentialTypesCredentialTypesCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/credential_types/][%d] credentialTypesCredentialTypesCreateForbidden ", 403)
}

func (o *CredentialTypesCredentialTypesCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
