// Code generated by go-swagger; DO NOT EDIT.

package credential_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialTypesCredentialTypesActivityStreamListReader is a Reader for the CredentialTypesCredentialTypesActivityStreamList structure.
type CredentialTypesCredentialTypesActivityStreamListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialTypesCredentialTypesActivityStreamListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialTypesCredentialTypesActivityStreamListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCredentialTypesCredentialTypesActivityStreamListOK creates a CredentialTypesCredentialTypesActivityStreamListOK with default headers values
func NewCredentialTypesCredentialTypesActivityStreamListOK() *CredentialTypesCredentialTypesActivityStreamListOK {
	return &CredentialTypesCredentialTypesActivityStreamListOK{}
}

/*CredentialTypesCredentialTypesActivityStreamListOK handles this case with default header values.

OK
*/
type CredentialTypesCredentialTypesActivityStreamListOK struct {
}

func (o *CredentialTypesCredentialTypesActivityStreamListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/credential_types/{id}/activity_stream/][%d] credentialTypesCredentialTypesActivityStreamListOK ", 200)
}

func (o *CredentialTypesCredentialTypesActivityStreamListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
