// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListReader is a Reader for the WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedList structure.
type WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK creates a WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK() *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK {
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK{}
}

/*WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK handles this case with default header values.

OK
*/
type WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK struct {
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_job_templates/{id}/notification_templates_started/][%d] workflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK ", 200)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesStartedListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
