// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListReader is a Reader for the WorkflowJobTemplatesWorkflowJobTemplatesSchedulesList structure.
type WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK creates a WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK() *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK {
	return &WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK{}
}

/*WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK handles this case with default header values.

OK
*/
type WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK struct {
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_job_templates/{id}/schedules/][%d] workflowJobTemplatesWorkflowJobTemplatesSchedulesListOK ", 200)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesSchedulesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
