// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams creates a new WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams object
// with the default values initialized.
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams() *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	var ()
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithTimeout creates a new WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithTimeout(timeout time.Duration) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	var ()
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams{

		timeout: timeout,
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithContext creates a new WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithContext(ctx context.Context) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	var ()
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams{

		Context: ctx,
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithHTTPClient creates a new WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParamsWithHTTPClient(client *http.Client) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	var ()
	return &WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams{
		HTTPClient: client,
	}
}

/*WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams contains all the parameters to send to the API endpoint
for the workflow job templates workflow job templates notification templates approvals create operation typically these are written to a http.Request
*/
type WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams struct {

	/*Data*/
	Data interface{}
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WithTimeout(timeout time.Duration) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WithContext(ctx context.Context) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WithHTTPClient(client *http.Client) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WithData(data interface{}) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) SetData(data interface{}) {
	o.Data = data
}

// WithID adds the id to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WithID(id string) *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the workflow job templates workflow job templates notification templates approvals create params
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowJobTemplatesWorkflowJobTemplatesNotificationTemplatesApprovalsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
