// Code generated by go-swagger; DO NOT EDIT.

package workflow_job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateReader is a Reader for the WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreate structure.
type WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated creates a WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated() *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated {
	return &WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated{}
}

/*WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated handles this case with default header values.

WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated workflow job templates workflow job templates workflow nodes create created
*/
type WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated struct {
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/workflow_nodes/][%d] workflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated ", 201)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest creates a WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest with default headers values
func NewWorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest() *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest {
	return &WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest{}
}

/*WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest handles this case with default header values.

Bad Request
*/
type WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest struct {
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/workflow_job_templates/{id}/workflow_nodes/][%d] workflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest ", 400)
}

func (o *WorkflowJobTemplatesWorkflowJobTemplatesWorkflowNodesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
