// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProjectsProjectsReadReader is a Reader for the ProjectsProjectsRead structure.
type ProjectsProjectsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectsProjectsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsProjectsReadOK creates a ProjectsProjectsReadOK with default headers values
func NewProjectsProjectsReadOK() *ProjectsProjectsReadOK {
	return &ProjectsProjectsReadOK{}
}

/*ProjectsProjectsReadOK handles this case with default header values.

OK
*/
type ProjectsProjectsReadOK struct {
}

func (o *ProjectsProjectsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{id}/][%d] projectsProjectsReadOK ", 200)
}

func (o *ProjectsProjectsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
