// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProjectsProjectsCreateReader is a Reader for the ProjectsProjectsCreate structure.
type ProjectsProjectsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProjectsProjectsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 415:
		result := NewProjectsProjectsCreateUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsProjectsCreateCreated creates a ProjectsProjectsCreateCreated with default headers values
func NewProjectsProjectsCreateCreated() *ProjectsProjectsCreateCreated {
	return &ProjectsProjectsCreateCreated{}
}

/*ProjectsProjectsCreateCreated handles this case with default header values.

ProjectsProjectsCreateCreated projects projects create created
*/
type ProjectsProjectsCreateCreated struct {
}

func (o *ProjectsProjectsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/projects/][%d] projectsProjectsCreateCreated ", 201)
}

func (o *ProjectsProjectsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectsProjectsCreateUnsupportedMediaType creates a ProjectsProjectsCreateUnsupportedMediaType with default headers values
func NewProjectsProjectsCreateUnsupportedMediaType() *ProjectsProjectsCreateUnsupportedMediaType {
	return &ProjectsProjectsCreateUnsupportedMediaType{}
}

/*ProjectsProjectsCreateUnsupportedMediaType handles this case with default header values.

Unsupported Media Type
*/
type ProjectsProjectsCreateUnsupportedMediaType struct {
}

func (o *ProjectsProjectsCreateUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /api/v2/projects/][%d] projectsProjectsCreateUnsupportedMediaType ", 415)
}

func (o *ProjectsProjectsCreateUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
