// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProjectsProjectsInventoriesReadReader is a Reader for the ProjectsProjectsInventoriesRead structure.
type ProjectsProjectsInventoriesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsInventoriesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectsProjectsInventoriesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsProjectsInventoriesReadOK creates a ProjectsProjectsInventoriesReadOK with default headers values
func NewProjectsProjectsInventoriesReadOK() *ProjectsProjectsInventoriesReadOK {
	return &ProjectsProjectsInventoriesReadOK{}
}

/*ProjectsProjectsInventoriesReadOK handles this case with default header values.

OK
*/
type ProjectsProjectsInventoriesReadOK struct {
}

func (o *ProjectsProjectsInventoriesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{id}/inventories/][%d] projectsProjectsInventoriesReadOK ", 200)
}

func (o *ProjectsProjectsInventoriesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
