// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProjectsProjectsProjectUpdatesListReader is a Reader for the ProjectsProjectsProjectUpdatesList structure.
type ProjectsProjectsProjectUpdatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsProjectsProjectUpdatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectsProjectsProjectUpdatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsProjectsProjectUpdatesListOK creates a ProjectsProjectsProjectUpdatesListOK with default headers values
func NewProjectsProjectsProjectUpdatesListOK() *ProjectsProjectsProjectUpdatesListOK {
	return &ProjectsProjectsProjectUpdatesListOK{}
}

/*ProjectsProjectsProjectUpdatesListOK handles this case with default header values.

OK
*/
type ProjectsProjectsProjectUpdatesListOK struct {
}

func (o *ProjectsProjectsProjectUpdatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{id}/project_updates/][%d] projectsProjectsProjectUpdatesListOK ", 200)
}

func (o *ProjectsProjectsProjectUpdatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
