// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProjectsProjectsNotificationTemplatesSuccessCreateParams creates a new ProjectsProjectsNotificationTemplatesSuccessCreateParams object
// with the default values initialized.
func NewProjectsProjectsNotificationTemplatesSuccessCreateParams() *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	var ()
	return &ProjectsProjectsNotificationTemplatesSuccessCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithTimeout creates a new ProjectsProjectsNotificationTemplatesSuccessCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithTimeout(timeout time.Duration) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	var ()
	return &ProjectsProjectsNotificationTemplatesSuccessCreateParams{

		timeout: timeout,
	}
}

// NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithContext creates a new ProjectsProjectsNotificationTemplatesSuccessCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithContext(ctx context.Context) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	var ()
	return &ProjectsProjectsNotificationTemplatesSuccessCreateParams{

		Context: ctx,
	}
}

// NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithHTTPClient creates a new ProjectsProjectsNotificationTemplatesSuccessCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsProjectsNotificationTemplatesSuccessCreateParamsWithHTTPClient(client *http.Client) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	var ()
	return &ProjectsProjectsNotificationTemplatesSuccessCreateParams{
		HTTPClient: client,
	}
}

/*ProjectsProjectsNotificationTemplatesSuccessCreateParams contains all the parameters to send to the API endpoint
for the projects projects notification templates success create operation typically these are written to a http.Request
*/
type ProjectsProjectsNotificationTemplatesSuccessCreateParams struct {

	/*Data*/
	Data ProjectsProjectsNotificationTemplatesSuccessCreateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WithTimeout(timeout time.Duration) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WithContext(ctx context.Context) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WithHTTPClient(client *http.Client) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WithData(data ProjectsProjectsNotificationTemplatesSuccessCreateBody) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) SetData(data ProjectsProjectsNotificationTemplatesSuccessCreateBody) {
	o.Data = data
}

// WithID adds the id to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WithID(id string) *ProjectsProjectsNotificationTemplatesSuccessCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the projects projects notification templates success create params
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsProjectsNotificationTemplatesSuccessCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
