// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsGroupsChildrenListReader is a Reader for the GroupsGroupsChildrenList structure.
type GroupsGroupsChildrenListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsGroupsChildrenListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsGroupsChildrenListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupsGroupsChildrenListOK creates a GroupsGroupsChildrenListOK with default headers values
func NewGroupsGroupsChildrenListOK() *GroupsGroupsChildrenListOK {
	return &GroupsGroupsChildrenListOK{}
}

/*GroupsGroupsChildrenListOK handles this case with default header values.

OK
*/
type GroupsGroupsChildrenListOK struct {
}

func (o *GroupsGroupsChildrenListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{id}/children/][%d] groupsGroupsChildrenListOK ", 200)
}

func (o *GroupsGroupsChildrenListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
