// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsGroupsHostsCreateReader is a Reader for the GroupsGroupsHostsCreate structure.
type GroupsGroupsHostsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsGroupsHostsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGroupsGroupsHostsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGroupsGroupsHostsCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupsGroupsHostsCreateCreated creates a GroupsGroupsHostsCreateCreated with default headers values
func NewGroupsGroupsHostsCreateCreated() *GroupsGroupsHostsCreateCreated {
	return &GroupsGroupsHostsCreateCreated{}
}

/*GroupsGroupsHostsCreateCreated handles this case with default header values.

GroupsGroupsHostsCreateCreated groups groups hosts create created
*/
type GroupsGroupsHostsCreateCreated struct {
}

func (o *GroupsGroupsHostsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/groups/{id}/hosts/][%d] groupsGroupsHostsCreateCreated ", 201)
}

func (o *GroupsGroupsHostsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGroupsGroupsHostsCreateForbidden creates a GroupsGroupsHostsCreateForbidden with default headers values
func NewGroupsGroupsHostsCreateForbidden() *GroupsGroupsHostsCreateForbidden {
	return &GroupsGroupsHostsCreateForbidden{}
}

/*GroupsGroupsHostsCreateForbidden handles this case with default header values.

No Permission Response
*/
type GroupsGroupsHostsCreateForbidden struct {
}

func (o *GroupsGroupsHostsCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/groups/{id}/hosts/][%d] groupsGroupsHostsCreateForbidden ", 403)
}

func (o *GroupsGroupsHostsCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
