// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstancesInstancesPartialUpdateReader is a Reader for the InstancesInstancesPartialUpdate structure.
type InstancesInstancesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstancesInstancesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstancesInstancesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInstancesInstancesPartialUpdateOK creates a InstancesInstancesPartialUpdateOK with default headers values
func NewInstancesInstancesPartialUpdateOK() *InstancesInstancesPartialUpdateOK {
	return &InstancesInstancesPartialUpdateOK{}
}

/*InstancesInstancesPartialUpdateOK handles this case with default header values.

OK
*/
type InstancesInstancesPartialUpdateOK struct {
}

func (o *InstancesInstancesPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/instances/{id}/][%d] instancesInstancesPartialUpdateOK ", 200)
}

func (o *InstancesInstancesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*InstancesInstancesPartialUpdateBody instances instances partial update body
swagger:model InstancesInstancesPartialUpdateBody
*/
type InstancesInstancesPartialUpdateBody struct {

	// capacity adjustment
	CapacityAdjustment float64 `json:"capacity_adjustment,omitempty"`

	// enabled
	Enabled string `json:"enabled,omitempty"`

	// managed by policy
	ManagedByPolicy string `json:"managed_by_policy,omitempty"`
}

// Validate validates this instances instances partial update body
func (o *InstancesInstancesPartialUpdateBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InstancesInstancesPartialUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InstancesInstancesPartialUpdateBody) UnmarshalBinary(b []byte) error {
	var res InstancesInstancesPartialUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
