// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInstancesInstancesInstanceGroupsCreateParams creates a new InstancesInstancesInstanceGroupsCreateParams object
// with the default values initialized.
func NewInstancesInstancesInstanceGroupsCreateParams() *InstancesInstancesInstanceGroupsCreateParams {
	var ()
	return &InstancesInstancesInstanceGroupsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInstancesInstancesInstanceGroupsCreateParamsWithTimeout creates a new InstancesInstancesInstanceGroupsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInstancesInstancesInstanceGroupsCreateParamsWithTimeout(timeout time.Duration) *InstancesInstancesInstanceGroupsCreateParams {
	var ()
	return &InstancesInstancesInstanceGroupsCreateParams{

		timeout: timeout,
	}
}

// NewInstancesInstancesInstanceGroupsCreateParamsWithContext creates a new InstancesInstancesInstanceGroupsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewInstancesInstancesInstanceGroupsCreateParamsWithContext(ctx context.Context) *InstancesInstancesInstanceGroupsCreateParams {
	var ()
	return &InstancesInstancesInstanceGroupsCreateParams{

		Context: ctx,
	}
}

// NewInstancesInstancesInstanceGroupsCreateParamsWithHTTPClient creates a new InstancesInstancesInstanceGroupsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInstancesInstancesInstanceGroupsCreateParamsWithHTTPClient(client *http.Client) *InstancesInstancesInstanceGroupsCreateParams {
	var ()
	return &InstancesInstancesInstanceGroupsCreateParams{
		HTTPClient: client,
	}
}

/*InstancesInstancesInstanceGroupsCreateParams contains all the parameters to send to the API endpoint
for the instances instances instance groups create operation typically these are written to a http.Request
*/
type InstancesInstancesInstanceGroupsCreateParams struct {

	/*Data*/
	Data InstancesInstancesInstanceGroupsCreateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) WithTimeout(timeout time.Duration) *InstancesInstancesInstanceGroupsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) WithContext(ctx context.Context) *InstancesInstancesInstanceGroupsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) WithHTTPClient(client *http.Client) *InstancesInstancesInstanceGroupsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) WithData(data InstancesInstancesInstanceGroupsCreateBody) *InstancesInstancesInstanceGroupsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) SetData(data InstancesInstancesInstanceGroupsCreateBody) {
	o.Data = data
}

// WithID adds the id to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) WithID(id string) *InstancesInstancesInstanceGroupsCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the instances instances instance groups create params
func (o *InstancesInstancesInstanceGroupsCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *InstancesInstancesInstanceGroupsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
