// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsInstanceGroupsCreateReader is a Reader for the OrganizationsOrganizationsInstanceGroupsCreate structure.
type OrganizationsOrganizationsInstanceGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsInstanceGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrganizationsOrganizationsInstanceGroupsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrganizationsOrganizationsInstanceGroupsCreateCreated creates a OrganizationsOrganizationsInstanceGroupsCreateCreated with default headers values
func NewOrganizationsOrganizationsInstanceGroupsCreateCreated() *OrganizationsOrganizationsInstanceGroupsCreateCreated {
	return &OrganizationsOrganizationsInstanceGroupsCreateCreated{}
}

/*OrganizationsOrganizationsInstanceGroupsCreateCreated handles this case with default header values.

OrganizationsOrganizationsInstanceGroupsCreateCreated organizations organizations instance groups create created
*/
type OrganizationsOrganizationsInstanceGroupsCreateCreated struct {
}

func (o *OrganizationsOrganizationsInstanceGroupsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/organizations/{id}/instance_groups/][%d] organizationsOrganizationsInstanceGroupsCreateCreated ", 201)
}

func (o *OrganizationsOrganizationsInstanceGroupsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
