// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrganizationsOrganizationsDeleteParams creates a new OrganizationsOrganizationsDeleteParams object
// with the default values initialized.
func NewOrganizationsOrganizationsDeleteParams() *OrganizationsOrganizationsDeleteParams {
	var ()
	return &OrganizationsOrganizationsDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationsOrganizationsDeleteParamsWithTimeout creates a new OrganizationsOrganizationsDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrganizationsOrganizationsDeleteParamsWithTimeout(timeout time.Duration) *OrganizationsOrganizationsDeleteParams {
	var ()
	return &OrganizationsOrganizationsDeleteParams{

		timeout: timeout,
	}
}

// NewOrganizationsOrganizationsDeleteParamsWithContext creates a new OrganizationsOrganizationsDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrganizationsOrganizationsDeleteParamsWithContext(ctx context.Context) *OrganizationsOrganizationsDeleteParams {
	var ()
	return &OrganizationsOrganizationsDeleteParams{

		Context: ctx,
	}
}

// NewOrganizationsOrganizationsDeleteParamsWithHTTPClient creates a new OrganizationsOrganizationsDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrganizationsOrganizationsDeleteParamsWithHTTPClient(client *http.Client) *OrganizationsOrganizationsDeleteParams {
	var ()
	return &OrganizationsOrganizationsDeleteParams{
		HTTPClient: client,
	}
}

/*OrganizationsOrganizationsDeleteParams contains all the parameters to send to the API endpoint
for the organizations organizations delete operation typically these are written to a http.Request
*/
type OrganizationsOrganizationsDeleteParams struct {

	/*ID*/
	ID string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) WithTimeout(timeout time.Duration) *OrganizationsOrganizationsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) WithContext(ctx context.Context) *OrganizationsOrganizationsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) WithHTTPClient(client *http.Client) *OrganizationsOrganizationsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) WithID(id string) *OrganizationsOrganizationsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) WithSearch(search *string) *OrganizationsOrganizationsDeleteParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the organizations organizations delete params
func (o *OrganizationsOrganizationsDeleteParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationsOrganizationsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
