// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsWorkflowJobTemplatesListReader is a Reader for the OrganizationsOrganizationsWorkflowJobTemplatesList structure.
type OrganizationsOrganizationsWorkflowJobTemplatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsWorkflowJobTemplatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsWorkflowJobTemplatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrganizationsOrganizationsWorkflowJobTemplatesListOK creates a OrganizationsOrganizationsWorkflowJobTemplatesListOK with default headers values
func NewOrganizationsOrganizationsWorkflowJobTemplatesListOK() *OrganizationsOrganizationsWorkflowJobTemplatesListOK {
	return &OrganizationsOrganizationsWorkflowJobTemplatesListOK{}
}

/*OrganizationsOrganizationsWorkflowJobTemplatesListOK handles this case with default header values.

OK
*/
type OrganizationsOrganizationsWorkflowJobTemplatesListOK struct {
}

func (o *OrganizationsOrganizationsWorkflowJobTemplatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/workflow_job_templates/][%d] organizationsOrganizationsWorkflowJobTemplatesListOK ", 200)
}

func (o *OrganizationsOrganizationsWorkflowJobTemplatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
