// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrganizationsOrganizationsInstanceGroupsListReader is a Reader for the OrganizationsOrganizationsInstanceGroupsList structure.
type OrganizationsOrganizationsInstanceGroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationsOrganizationsInstanceGroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationsOrganizationsInstanceGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrganizationsOrganizationsInstanceGroupsListOK creates a OrganizationsOrganizationsInstanceGroupsListOK with default headers values
func NewOrganizationsOrganizationsInstanceGroupsListOK() *OrganizationsOrganizationsInstanceGroupsListOK {
	return &OrganizationsOrganizationsInstanceGroupsListOK{}
}

/*OrganizationsOrganizationsInstanceGroupsListOK handles this case with default header values.

OK
*/
type OrganizationsOrganizationsInstanceGroupsListOK struct {
}

func (o *OrganizationsOrganizationsInstanceGroupsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{id}/instance_groups/][%d] organizationsOrganizationsInstanceGroupsListOK ", 200)
}

func (o *OrganizationsOrganizationsInstanceGroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
