// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJobsJobsRelaunchReadParams creates a new JobsJobsRelaunchReadParams object
// with the default values initialized.
func NewJobsJobsRelaunchReadParams() *JobsJobsRelaunchReadParams {
	var ()
	return &JobsJobsRelaunchReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobsJobsRelaunchReadParamsWithTimeout creates a new JobsJobsRelaunchReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobsJobsRelaunchReadParamsWithTimeout(timeout time.Duration) *JobsJobsRelaunchReadParams {
	var ()
	return &JobsJobsRelaunchReadParams{

		timeout: timeout,
	}
}

// NewJobsJobsRelaunchReadParamsWithContext creates a new JobsJobsRelaunchReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobsJobsRelaunchReadParamsWithContext(ctx context.Context) *JobsJobsRelaunchReadParams {
	var ()
	return &JobsJobsRelaunchReadParams{

		Context: ctx,
	}
}

// NewJobsJobsRelaunchReadParamsWithHTTPClient creates a new JobsJobsRelaunchReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobsJobsRelaunchReadParamsWithHTTPClient(client *http.Client) *JobsJobsRelaunchReadParams {
	var ()
	return &JobsJobsRelaunchReadParams{
		HTTPClient: client,
	}
}

/*JobsJobsRelaunchReadParams contains all the parameters to send to the API endpoint
for the jobs jobs relaunch read operation typically these are written to a http.Request
*/
type JobsJobsRelaunchReadParams struct {

	/*ID*/
	ID string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) WithTimeout(timeout time.Duration) *JobsJobsRelaunchReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) WithContext(ctx context.Context) *JobsJobsRelaunchReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) WithHTTPClient(client *http.Client) *JobsJobsRelaunchReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) WithID(id string) *JobsJobsRelaunchReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) WithSearch(search *string) *JobsJobsRelaunchReadParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the jobs jobs relaunch read params
func (o *JobsJobsRelaunchReadParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *JobsJobsRelaunchReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
