// Code generated by go-swagger; DO NOT EDIT.

package workflow_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewWorkflowJobsWorkflowJobsListParams creates a new WorkflowJobsWorkflowJobsListParams object
// with the default values initialized.
func NewWorkflowJobsWorkflowJobsListParams() *WorkflowJobsWorkflowJobsListParams {
	var ()
	return &WorkflowJobsWorkflowJobsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowJobsWorkflowJobsListParamsWithTimeout creates a new WorkflowJobsWorkflowJobsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWorkflowJobsWorkflowJobsListParamsWithTimeout(timeout time.Duration) *WorkflowJobsWorkflowJobsListParams {
	var ()
	return &WorkflowJobsWorkflowJobsListParams{

		timeout: timeout,
	}
}

// NewWorkflowJobsWorkflowJobsListParamsWithContext creates a new WorkflowJobsWorkflowJobsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewWorkflowJobsWorkflowJobsListParamsWithContext(ctx context.Context) *WorkflowJobsWorkflowJobsListParams {
	var ()
	return &WorkflowJobsWorkflowJobsListParams{

		Context: ctx,
	}
}

// NewWorkflowJobsWorkflowJobsListParamsWithHTTPClient creates a new WorkflowJobsWorkflowJobsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWorkflowJobsWorkflowJobsListParamsWithHTTPClient(client *http.Client) *WorkflowJobsWorkflowJobsListParams {
	var ()
	return &WorkflowJobsWorkflowJobsListParams{
		HTTPClient: client,
	}
}

/*WorkflowJobsWorkflowJobsListParams contains all the parameters to send to the API endpoint
for the workflow jobs workflow jobs list operation typically these are written to a http.Request
*/
type WorkflowJobsWorkflowJobsListParams struct {

	/*Page
	  A page number within the paginated result set.

	*/
	Page *int64
	/*PageSize
	  Number of results to return per page.

	*/
	PageSize *int64
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithTimeout(timeout time.Duration) *WorkflowJobsWorkflowJobsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithContext(ctx context.Context) *WorkflowJobsWorkflowJobsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithHTTPClient(client *http.Client) *WorkflowJobsWorkflowJobsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithPage(page *int64) *WorkflowJobsWorkflowJobsListParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithPageSize(pageSize *int64) *WorkflowJobsWorkflowJobsListParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSearch adds the search to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) WithSearch(search *string) *WorkflowJobsWorkflowJobsListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the workflow jobs workflow jobs list params
func (o *WorkflowJobsWorkflowJobsListParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowJobsWorkflowJobsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
