// Code generated by go-swagger; DO NOT EDIT.

package workflow_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobsWorkflowJobsReadReader is a Reader for the WorkflowJobsWorkflowJobsRead structure.
type WorkflowJobsWorkflowJobsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobsWorkflowJobsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowJobsWorkflowJobsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowJobsWorkflowJobsReadOK creates a WorkflowJobsWorkflowJobsReadOK with default headers values
func NewWorkflowJobsWorkflowJobsReadOK() *WorkflowJobsWorkflowJobsReadOK {
	return &WorkflowJobsWorkflowJobsReadOK{}
}

/*WorkflowJobsWorkflowJobsReadOK handles this case with default header values.

OK
*/
type WorkflowJobsWorkflowJobsReadOK struct {
}

func (o *WorkflowJobsWorkflowJobsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_jobs/{id}/][%d] workflowJobsWorkflowJobsReadOK ", 200)
}

func (o *WorkflowJobsWorkflowJobsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
