// Code generated by go-swagger; DO NOT EDIT.

package workflow_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowJobsWorkflowJobsDeleteReader is a Reader for the WorkflowJobsWorkflowJobsDelete structure.
type WorkflowJobsWorkflowJobsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowJobsWorkflowJobsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewWorkflowJobsWorkflowJobsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewWorkflowJobsWorkflowJobsDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowJobsWorkflowJobsDeleteNoContent creates a WorkflowJobsWorkflowJobsDeleteNoContent with default headers values
func NewWorkflowJobsWorkflowJobsDeleteNoContent() *WorkflowJobsWorkflowJobsDeleteNoContent {
	return &WorkflowJobsWorkflowJobsDeleteNoContent{}
}

/*WorkflowJobsWorkflowJobsDeleteNoContent handles this case with default header values.

WorkflowJobsWorkflowJobsDeleteNoContent workflow jobs workflow jobs delete no content
*/
type WorkflowJobsWorkflowJobsDeleteNoContent struct {
}

func (o *WorkflowJobsWorkflowJobsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/workflow_jobs/{id}/][%d] workflowJobsWorkflowJobsDeleteNoContent ", 204)
}

func (o *WorkflowJobsWorkflowJobsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWorkflowJobsWorkflowJobsDeleteForbidden creates a WorkflowJobsWorkflowJobsDeleteForbidden with default headers values
func NewWorkflowJobsWorkflowJobsDeleteForbidden() *WorkflowJobsWorkflowJobsDeleteForbidden {
	return &WorkflowJobsWorkflowJobsDeleteForbidden{}
}

/*WorkflowJobsWorkflowJobsDeleteForbidden handles this case with default header values.

No Permission Response
*/
type WorkflowJobsWorkflowJobsDeleteForbidden struct {
}

func (o *WorkflowJobsWorkflowJobsDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/workflow_jobs/{id}/][%d] workflowJobsWorkflowJobsDeleteForbidden ", 403)
}

func (o *WorkflowJobsWorkflowJobsDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
