// Code generated by go-swagger; DO NOT EDIT.

package ad_hoc_command_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAdHocCommandEventsAdHocCommandEventsReadParams creates a new AdHocCommandEventsAdHocCommandEventsReadParams object
// with the default values initialized.
func NewAdHocCommandEventsAdHocCommandEventsReadParams() *AdHocCommandEventsAdHocCommandEventsReadParams {
	var ()
	return &AdHocCommandEventsAdHocCommandEventsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAdHocCommandEventsAdHocCommandEventsReadParamsWithTimeout creates a new AdHocCommandEventsAdHocCommandEventsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAdHocCommandEventsAdHocCommandEventsReadParamsWithTimeout(timeout time.Duration) *AdHocCommandEventsAdHocCommandEventsReadParams {
	var ()
	return &AdHocCommandEventsAdHocCommandEventsReadParams{

		timeout: timeout,
	}
}

// NewAdHocCommandEventsAdHocCommandEventsReadParamsWithContext creates a new AdHocCommandEventsAdHocCommandEventsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewAdHocCommandEventsAdHocCommandEventsReadParamsWithContext(ctx context.Context) *AdHocCommandEventsAdHocCommandEventsReadParams {
	var ()
	return &AdHocCommandEventsAdHocCommandEventsReadParams{

		Context: ctx,
	}
}

// NewAdHocCommandEventsAdHocCommandEventsReadParamsWithHTTPClient creates a new AdHocCommandEventsAdHocCommandEventsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAdHocCommandEventsAdHocCommandEventsReadParamsWithHTTPClient(client *http.Client) *AdHocCommandEventsAdHocCommandEventsReadParams {
	var ()
	return &AdHocCommandEventsAdHocCommandEventsReadParams{
		HTTPClient: client,
	}
}

/*AdHocCommandEventsAdHocCommandEventsReadParams contains all the parameters to send to the API endpoint
for the ad hoc command events ad hoc command events read operation typically these are written to a http.Request
*/
type AdHocCommandEventsAdHocCommandEventsReadParams struct {

	/*ID*/
	ID string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WithTimeout(timeout time.Duration) *AdHocCommandEventsAdHocCommandEventsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WithContext(ctx context.Context) *AdHocCommandEventsAdHocCommandEventsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WithHTTPClient(client *http.Client) *AdHocCommandEventsAdHocCommandEventsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WithID(id string) *AdHocCommandEventsAdHocCommandEventsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WithSearch(search *string) *AdHocCommandEventsAdHocCommandEventsReadParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the ad hoc command events ad hoc command events read params
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *AdHocCommandEventsAdHocCommandEventsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
