// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsDeleteReader is a Reader for the HostsHostsDelete structure.
type HostsHostsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewHostsHostsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewHostsHostsDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewHostsHostsDeleteNoContent creates a HostsHostsDeleteNoContent with default headers values
func NewHostsHostsDeleteNoContent() *HostsHostsDeleteNoContent {
	return &HostsHostsDeleteNoContent{}
}

/*HostsHostsDeleteNoContent handles this case with default header values.

HostsHostsDeleteNoContent hosts hosts delete no content
*/
type HostsHostsDeleteNoContent struct {
}

func (o *HostsHostsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/hosts/{id}/][%d] hostsHostsDeleteNoContent ", 204)
}

func (o *HostsHostsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHostsHostsDeleteForbidden creates a HostsHostsDeleteForbidden with default headers values
func NewHostsHostsDeleteForbidden() *HostsHostsDeleteForbidden {
	return &HostsHostsDeleteForbidden{}
}

/*HostsHostsDeleteForbidden handles this case with default header values.

No Permission Response
*/
type HostsHostsDeleteForbidden struct {
}

func (o *HostsHostsDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/hosts/{id}/][%d] hostsHostsDeleteForbidden ", 403)
}

func (o *HostsHostsDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
