// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HostsHostsSmartInventoriesListReader is a Reader for the HostsHostsSmartInventoriesList structure.
type HostsHostsSmartInventoriesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostsHostsSmartInventoriesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHostsHostsSmartInventoriesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewHostsHostsSmartInventoriesListOK creates a HostsHostsSmartInventoriesListOK with default headers values
func NewHostsHostsSmartInventoriesListOK() *HostsHostsSmartInventoriesListOK {
	return &HostsHostsSmartInventoriesListOK{}
}

/*HostsHostsSmartInventoriesListOK handles this case with default header values.

OK
*/
type HostsHostsSmartInventoriesListOK struct {
}

func (o *HostsHostsSmartInventoriesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/hosts/{id}/smart_inventories/][%d] hostsHostsSmartInventoriesListOK ", 200)
}

func (o *HostsHostsSmartInventoriesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
