// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuthenticationApplicationsPartialUpdate0Reader is a Reader for the AuthenticationApplicationsPartialUpdate0 structure.
type AuthenticationApplicationsPartialUpdate0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthenticationApplicationsPartialUpdate0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthenticationApplicationsPartialUpdate0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAuthenticationApplicationsPartialUpdate0OK creates a AuthenticationApplicationsPartialUpdate0OK with default headers values
func NewAuthenticationApplicationsPartialUpdate0OK() *AuthenticationApplicationsPartialUpdate0OK {
	return &AuthenticationApplicationsPartialUpdate0OK{}
}

/*AuthenticationApplicationsPartialUpdate0OK handles this case with default header values.

OK
*/
type AuthenticationApplicationsPartialUpdate0OK struct {
}

func (o *AuthenticationApplicationsPartialUpdate0OK) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/applications/{id}/][%d] authenticationApplicationsPartialUpdate0OK ", 200)
}

func (o *AuthenticationApplicationsPartialUpdate0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
