// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CredentialsCredentialsListReader is a Reader for the CredentialsCredentialsList structure.
type CredentialsCredentialsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialsCredentialsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialsCredentialsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCredentialsCredentialsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCredentialsCredentialsListOK creates a CredentialsCredentialsListOK with default headers values
func NewCredentialsCredentialsListOK() *CredentialsCredentialsListOK {
	return &CredentialsCredentialsListOK{}
}

/*CredentialsCredentialsListOK handles this case with default header values.

OK
*/
type CredentialsCredentialsListOK struct {
}

func (o *CredentialsCredentialsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/credentials/][%d] credentialsCredentialsListOK ", 200)
}

func (o *CredentialsCredentialsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCredentialsCredentialsListBadRequest creates a CredentialsCredentialsListBadRequest with default headers values
func NewCredentialsCredentialsListBadRequest() *CredentialsCredentialsListBadRequest {
	return &CredentialsCredentialsListBadRequest{}
}

/*CredentialsCredentialsListBadRequest handles this case with default header values.

Bad Request
*/
type CredentialsCredentialsListBadRequest struct {
}

func (o *CredentialsCredentialsListBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/credentials/][%d] credentialsCredentialsListBadRequest ", 400)
}

func (o *CredentialsCredentialsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
