// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUsersUsersDeleteParams creates a new UsersUsersDeleteParams object
// with the default values initialized.
func NewUsersUsersDeleteParams() *UsersUsersDeleteParams {
	var ()
	return &UsersUsersDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersUsersDeleteParamsWithTimeout creates a new UsersUsersDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersUsersDeleteParamsWithTimeout(timeout time.Duration) *UsersUsersDeleteParams {
	var ()
	return &UsersUsersDeleteParams{

		timeout: timeout,
	}
}

// NewUsersUsersDeleteParamsWithContext creates a new UsersUsersDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersUsersDeleteParamsWithContext(ctx context.Context) *UsersUsersDeleteParams {
	var ()
	return &UsersUsersDeleteParams{

		Context: ctx,
	}
}

// NewUsersUsersDeleteParamsWithHTTPClient creates a new UsersUsersDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersUsersDeleteParamsWithHTTPClient(client *http.Client) *UsersUsersDeleteParams {
	var ()
	return &UsersUsersDeleteParams{
		HTTPClient: client,
	}
}

/*UsersUsersDeleteParams contains all the parameters to send to the API endpoint
for the users users delete operation typically these are written to a http.Request
*/
type UsersUsersDeleteParams struct {

	/*ID*/
	ID string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users users delete params
func (o *UsersUsersDeleteParams) WithTimeout(timeout time.Duration) *UsersUsersDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users users delete params
func (o *UsersUsersDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users users delete params
func (o *UsersUsersDeleteParams) WithContext(ctx context.Context) *UsersUsersDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users users delete params
func (o *UsersUsersDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users users delete params
func (o *UsersUsersDeleteParams) WithHTTPClient(client *http.Client) *UsersUsersDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users users delete params
func (o *UsersUsersDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the users users delete params
func (o *UsersUsersDeleteParams) WithID(id string) *UsersUsersDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users users delete params
func (o *UsersUsersDeleteParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the users users delete params
func (o *UsersUsersDeleteParams) WithSearch(search *string) *UsersUsersDeleteParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the users users delete params
func (o *UsersUsersDeleteParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *UsersUsersDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
