// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersUsersActivityStreamListReader is a Reader for the UsersUsersActivityStreamList structure.
type UsersUsersActivityStreamListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersUsersActivityStreamListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersUsersActivityStreamListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersUsersActivityStreamListOK creates a UsersUsersActivityStreamListOK with default headers values
func NewUsersUsersActivityStreamListOK() *UsersUsersActivityStreamListOK {
	return &UsersUsersActivityStreamListOK{}
}

/*UsersUsersActivityStreamListOK handles this case with default header values.

OK
*/
type UsersUsersActivityStreamListOK struct {
}

func (o *UsersUsersActivityStreamListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/users/{id}/activity_stream/][%d] usersUsersActivityStreamListOK ", 200)
}

func (o *UsersUsersActivityStreamListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
