// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUsersUsersRolesCreateParams creates a new UsersUsersRolesCreateParams object
// with the default values initialized.
func NewUsersUsersRolesCreateParams() *UsersUsersRolesCreateParams {
	var ()
	return &UsersUsersRolesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersUsersRolesCreateParamsWithTimeout creates a new UsersUsersRolesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersUsersRolesCreateParamsWithTimeout(timeout time.Duration) *UsersUsersRolesCreateParams {
	var ()
	return &UsersUsersRolesCreateParams{

		timeout: timeout,
	}
}

// NewUsersUsersRolesCreateParamsWithContext creates a new UsersUsersRolesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersUsersRolesCreateParamsWithContext(ctx context.Context) *UsersUsersRolesCreateParams {
	var ()
	return &UsersUsersRolesCreateParams{

		Context: ctx,
	}
}

// NewUsersUsersRolesCreateParamsWithHTTPClient creates a new UsersUsersRolesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersUsersRolesCreateParamsWithHTTPClient(client *http.Client) *UsersUsersRolesCreateParams {
	var ()
	return &UsersUsersRolesCreateParams{
		HTTPClient: client,
	}
}

/*UsersUsersRolesCreateParams contains all the parameters to send to the API endpoint
for the users users roles create operation typically these are written to a http.Request
*/
type UsersUsersRolesCreateParams struct {

	/*Data*/
	Data interface{}
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users users roles create params
func (o *UsersUsersRolesCreateParams) WithTimeout(timeout time.Duration) *UsersUsersRolesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users users roles create params
func (o *UsersUsersRolesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users users roles create params
func (o *UsersUsersRolesCreateParams) WithContext(ctx context.Context) *UsersUsersRolesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users users roles create params
func (o *UsersUsersRolesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users users roles create params
func (o *UsersUsersRolesCreateParams) WithHTTPClient(client *http.Client) *UsersUsersRolesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users users roles create params
func (o *UsersUsersRolesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the users users roles create params
func (o *UsersUsersRolesCreateParams) WithData(data interface{}) *UsersUsersRolesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the users users roles create params
func (o *UsersUsersRolesCreateParams) SetData(data interface{}) {
	o.Data = data
}

// WithID adds the id to the users users roles create params
func (o *UsersUsersRolesCreateParams) WithID(id string) *UsersUsersRolesCreateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users users roles create params
func (o *UsersUsersRolesCreateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UsersUsersRolesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
