// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJobTemplatesJobTemplatesPartialUpdateParams creates a new JobTemplatesJobTemplatesPartialUpdateParams object
// with the default values initialized.
func NewJobTemplatesJobTemplatesPartialUpdateParams() *JobTemplatesJobTemplatesPartialUpdateParams {
	var ()
	return &JobTemplatesJobTemplatesPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobTemplatesJobTemplatesPartialUpdateParamsWithTimeout creates a new JobTemplatesJobTemplatesPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobTemplatesJobTemplatesPartialUpdateParamsWithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesPartialUpdateParams {
	var ()
	return &JobTemplatesJobTemplatesPartialUpdateParams{

		timeout: timeout,
	}
}

// NewJobTemplatesJobTemplatesPartialUpdateParamsWithContext creates a new JobTemplatesJobTemplatesPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobTemplatesJobTemplatesPartialUpdateParamsWithContext(ctx context.Context) *JobTemplatesJobTemplatesPartialUpdateParams {
	var ()
	return &JobTemplatesJobTemplatesPartialUpdateParams{

		Context: ctx,
	}
}

// NewJobTemplatesJobTemplatesPartialUpdateParamsWithHTTPClient creates a new JobTemplatesJobTemplatesPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobTemplatesJobTemplatesPartialUpdateParamsWithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesPartialUpdateParams {
	var ()
	return &JobTemplatesJobTemplatesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*JobTemplatesJobTemplatesPartialUpdateParams contains all the parameters to send to the API endpoint
for the job templates job templates partial update operation typically these are written to a http.Request
*/
type JobTemplatesJobTemplatesPartialUpdateParams struct {

	/*Data*/
	Data interface{}
	/*ID*/
	ID string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithContext(ctx context.Context) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithData(data interface{}) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetData(data interface{}) {
	o.Data = data
}

// WithID adds the id to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithID(id string) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WithSearch adds the search to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WithSearch(search *string) *JobTemplatesJobTemplatesPartialUpdateParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the job templates job templates partial update params
func (o *JobTemplatesJobTemplatesPartialUpdateParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *JobTemplatesJobTemplatesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
