// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobTemplatesJobTemplatesExtraCredentialsListReader is a Reader for the JobTemplatesJobTemplatesExtraCredentialsList structure.
type JobTemplatesJobTemplatesExtraCredentialsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobTemplatesJobTemplatesExtraCredentialsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobTemplatesJobTemplatesExtraCredentialsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJobTemplatesJobTemplatesExtraCredentialsListOK creates a JobTemplatesJobTemplatesExtraCredentialsListOK with default headers values
func NewJobTemplatesJobTemplatesExtraCredentialsListOK() *JobTemplatesJobTemplatesExtraCredentialsListOK {
	return &JobTemplatesJobTemplatesExtraCredentialsListOK{}
}

/*JobTemplatesJobTemplatesExtraCredentialsListOK handles this case with default header values.

OK
*/
type JobTemplatesJobTemplatesExtraCredentialsListOK struct {
}

func (o *JobTemplatesJobTemplatesExtraCredentialsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/job_templates/{id}/extra_credentials/][%d] jobTemplatesJobTemplatesExtraCredentialsListOK ", 200)
}

func (o *JobTemplatesJobTemplatesExtraCredentialsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
