// Code generated by go-swagger; DO NOT EDIT.

package job_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewJobTemplatesJobTemplatesListParams creates a new JobTemplatesJobTemplatesListParams object
// with the default values initialized.
func NewJobTemplatesJobTemplatesListParams() *JobTemplatesJobTemplatesListParams {
	var ()
	return &JobTemplatesJobTemplatesListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobTemplatesJobTemplatesListParamsWithTimeout creates a new JobTemplatesJobTemplatesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobTemplatesJobTemplatesListParamsWithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesListParams {
	var ()
	return &JobTemplatesJobTemplatesListParams{

		timeout: timeout,
	}
}

// NewJobTemplatesJobTemplatesListParamsWithContext creates a new JobTemplatesJobTemplatesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobTemplatesJobTemplatesListParamsWithContext(ctx context.Context) *JobTemplatesJobTemplatesListParams {
	var ()
	return &JobTemplatesJobTemplatesListParams{

		Context: ctx,
	}
}

// NewJobTemplatesJobTemplatesListParamsWithHTTPClient creates a new JobTemplatesJobTemplatesListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobTemplatesJobTemplatesListParamsWithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesListParams {
	var ()
	return &JobTemplatesJobTemplatesListParams{
		HTTPClient: client,
	}
}

/*JobTemplatesJobTemplatesListParams contains all the parameters to send to the API endpoint
for the job templates job templates list operation typically these are written to a http.Request
*/
type JobTemplatesJobTemplatesListParams struct {

	/*Page
	  A page number within the paginated result set.

	*/
	Page *int64
	/*PageSize
	  Number of results to return per page.

	*/
	PageSize *int64
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithTimeout(timeout time.Duration) *JobTemplatesJobTemplatesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithContext(ctx context.Context) *JobTemplatesJobTemplatesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithHTTPClient(client *http.Client) *JobTemplatesJobTemplatesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithPage(page *int64) *JobTemplatesJobTemplatesListParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithPageSize(pageSize *int64) *JobTemplatesJobTemplatesListParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSearch adds the search to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) WithSearch(search *string) *JobTemplatesJobTemplatesListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the job templates job templates list params
func (o *JobTemplatesJobTemplatesListParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *JobTemplatesJobTemplatesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
