// Code generated by go-swagger; DO NOT EDIT.

package notification_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NotificationTemplatesNotificationTemplatesListReader is a Reader for the NotificationTemplatesNotificationTemplatesList structure.
type NotificationTemplatesNotificationTemplatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationTemplatesNotificationTemplatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNotificationTemplatesNotificationTemplatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewNotificationTemplatesNotificationTemplatesListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNotificationTemplatesNotificationTemplatesListOK creates a NotificationTemplatesNotificationTemplatesListOK with default headers values
func NewNotificationTemplatesNotificationTemplatesListOK() *NotificationTemplatesNotificationTemplatesListOK {
	return &NotificationTemplatesNotificationTemplatesListOK{}
}

/*NotificationTemplatesNotificationTemplatesListOK handles this case with default header values.

OK
*/
type NotificationTemplatesNotificationTemplatesListOK struct {
}

func (o *NotificationTemplatesNotificationTemplatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/notification_templates/][%d] notificationTemplatesNotificationTemplatesListOK ", 200)
}

func (o *NotificationTemplatesNotificationTemplatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNotificationTemplatesNotificationTemplatesListForbidden creates a NotificationTemplatesNotificationTemplatesListForbidden with default headers values
func NewNotificationTemplatesNotificationTemplatesListForbidden() *NotificationTemplatesNotificationTemplatesListForbidden {
	return &NotificationTemplatesNotificationTemplatesListForbidden{}
}

/*NotificationTemplatesNotificationTemplatesListForbidden handles this case with default header values.

No Permission Response
*/
type NotificationTemplatesNotificationTemplatesListForbidden struct {
}

func (o *NotificationTemplatesNotificationTemplatesListForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/notification_templates/][%d] notificationTemplatesNotificationTemplatesListForbidden ", 403)
}

func (o *NotificationTemplatesNotificationTemplatesListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
