// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TeamsTeamsAccessListListReader is a Reader for the TeamsTeamsAccessListList structure.
type TeamsTeamsAccessListListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsTeamsAccessListListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTeamsTeamsAccessListListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsTeamsAccessListListOK creates a TeamsTeamsAccessListListOK with default headers values
func NewTeamsTeamsAccessListListOK() *TeamsTeamsAccessListListOK {
	return &TeamsTeamsAccessListListOK{}
}

/*TeamsTeamsAccessListListOK handles this case with default header values.

OK
*/
type TeamsTeamsAccessListListOK struct {
}

func (o *TeamsTeamsAccessListListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/teams/{id}/access_list/][%d] teamsTeamsAccessListListOK ", 200)
}

func (o *TeamsTeamsAccessListListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
