// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TeamsTeamsDeleteReader is a Reader for the TeamsTeamsDelete structure.
type TeamsTeamsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsTeamsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewTeamsTeamsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsTeamsDeleteNoContent creates a TeamsTeamsDeleteNoContent with default headers values
func NewTeamsTeamsDeleteNoContent() *TeamsTeamsDeleteNoContent {
	return &TeamsTeamsDeleteNoContent{}
}

/*TeamsTeamsDeleteNoContent handles this case with default header values.

TeamsTeamsDeleteNoContent teams teams delete no content
*/
type TeamsTeamsDeleteNoContent struct {
}

func (o *TeamsTeamsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/teams/{id}/][%d] teamsTeamsDeleteNoContent ", 204)
}

func (o *TeamsTeamsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
