// Code generated by go-swagger; DO NOT EDIT.

package system_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SystemConfigurationAuthListReader is a Reader for the SystemConfigurationAuthList structure.
type SystemConfigurationAuthListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemConfigurationAuthListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemConfigurationAuthListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemConfigurationAuthListOK creates a SystemConfigurationAuthListOK with default headers values
func NewSystemConfigurationAuthListOK() *SystemConfigurationAuthListOK {
	return &SystemConfigurationAuthListOK{}
}

/*SystemConfigurationAuthListOK handles this case with default header values.

OK
*/
type SystemConfigurationAuthListOK struct {
}

func (o *SystemConfigurationAuthListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/auth/][%d] systemConfigurationAuthListOK ", 200)
}

func (o *SystemConfigurationAuthListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
