// Code generated by go-swagger; DO NOT EDIT.

package system_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SystemConfigurationConfigListReader is a Reader for the SystemConfigurationConfigList structure.
type SystemConfigurationConfigListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemConfigurationConfigListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemConfigurationConfigListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemConfigurationConfigListOK creates a SystemConfigurationConfigListOK with default headers values
func NewSystemConfigurationConfigListOK() *SystemConfigurationConfigListOK {
	return &SystemConfigurationConfigListOK{}
}

/*SystemConfigurationConfigListOK handles this case with default header values.

OK
*/
type SystemConfigurationConfigListOK struct {
}

func (o *SystemConfigurationConfigListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/config/][%d] systemConfigurationConfigListOK ", 200)
}

func (o *SystemConfigurationConfigListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
