// Code generated by go-swagger; DO NOT EDIT.

package system_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SystemConfigurationConfigCreateReader is a Reader for the SystemConfigurationConfigCreate structure.
type SystemConfigurationConfigCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemConfigurationConfigCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSystemConfigurationConfigCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemConfigurationConfigCreateCreated creates a SystemConfigurationConfigCreateCreated with default headers values
func NewSystemConfigurationConfigCreateCreated() *SystemConfigurationConfigCreateCreated {
	return &SystemConfigurationConfigCreateCreated{}
}

/*SystemConfigurationConfigCreateCreated handles this case with default header values.

SystemConfigurationConfigCreateCreated system configuration config create created
*/
type SystemConfigurationConfigCreateCreated struct {
}

func (o *SystemConfigurationConfigCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/config/][%d] systemConfigurationConfigCreateCreated ", 201)
}

func (o *SystemConfigurationConfigCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
