// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventoriesInventoriesVariableDataUpdateReader is a Reader for the InventoriesInventoriesVariableDataUpdate structure.
type InventoriesInventoriesVariableDataUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoriesInventoriesVariableDataUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventoriesInventoriesVariableDataUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewInventoriesInventoriesVariableDataUpdateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInventoriesInventoriesVariableDataUpdateOK creates a InventoriesInventoriesVariableDataUpdateOK with default headers values
func NewInventoriesInventoriesVariableDataUpdateOK() *InventoriesInventoriesVariableDataUpdateOK {
	return &InventoriesInventoriesVariableDataUpdateOK{}
}

/*InventoriesInventoriesVariableDataUpdateOK handles this case with default header values.

OK
*/
type InventoriesInventoriesVariableDataUpdateOK struct {
}

func (o *InventoriesInventoriesVariableDataUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/inventories/{id}/variable_data/][%d] inventoriesInventoriesVariableDataUpdateOK ", 200)
}

func (o *InventoriesInventoriesVariableDataUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInventoriesInventoriesVariableDataUpdateForbidden creates a InventoriesInventoriesVariableDataUpdateForbidden with default headers values
func NewInventoriesInventoriesVariableDataUpdateForbidden() *InventoriesInventoriesVariableDataUpdateForbidden {
	return &InventoriesInventoriesVariableDataUpdateForbidden{}
}

/*InventoriesInventoriesVariableDataUpdateForbidden handles this case with default header values.

No Permission Response
*/
type InventoriesInventoriesVariableDataUpdateForbidden struct {
}

func (o *InventoriesInventoriesVariableDataUpdateForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/v2/inventories/{id}/variable_data/][%d] inventoriesInventoriesVariableDataUpdateForbidden ", 403)
}

func (o *InventoriesInventoriesVariableDataUpdateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
