// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InventoriesInventoriesCopyListReader is a Reader for the InventoriesInventoriesCopyList structure.
type InventoriesInventoriesCopyListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoriesInventoriesCopyListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventoriesInventoriesCopyListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInventoriesInventoriesCopyListOK creates a InventoriesInventoriesCopyListOK with default headers values
func NewInventoriesInventoriesCopyListOK() *InventoriesInventoriesCopyListOK {
	return &InventoriesInventoriesCopyListOK{}
}

/*InventoriesInventoriesCopyListOK handles this case with default header values.

OK
*/
type InventoriesInventoriesCopyListOK struct {
}

func (o *InventoriesInventoriesCopyListOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/inventories/{id}/copy/][%d] inventoriesInventoriesCopyListOK ", 200)
}

func (o *InventoriesInventoriesCopyListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
