// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SettingsSettingsUpdateReader is a Reader for the SettingsSettingsUpdate structure.
type SettingsSettingsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettingsSettingsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSettingsSettingsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSettingsSettingsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSettingsSettingsUpdateOK creates a SettingsSettingsUpdateOK with default headers values
func NewSettingsSettingsUpdateOK() *SettingsSettingsUpdateOK {
	return &SettingsSettingsUpdateOK{}
}

/*SettingsSettingsUpdateOK handles this case with default header values.

OK
*/
type SettingsSettingsUpdateOK struct {
}

func (o *SettingsSettingsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateOK ", 200)
}

func (o *SettingsSettingsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettingsSettingsUpdateBadRequest creates a SettingsSettingsUpdateBadRequest with default headers values
func NewSettingsSettingsUpdateBadRequest() *SettingsSettingsUpdateBadRequest {
	return &SettingsSettingsUpdateBadRequest{}
}

/*SettingsSettingsUpdateBadRequest handles this case with default header values.

Bad Request
*/
type SettingsSettingsUpdateBadRequest struct {
}

func (o *SettingsSettingsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/settings/{category_slug}/][%d] settingsSettingsUpdateBadRequest ", 400)
}

func (o *SettingsSettingsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
