// Code generated by go-swagger; DO NOT EDIT.

package workflow_approvals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WorkflowApprovalsWorkflowApprovalsApproveReadReader is a Reader for the WorkflowApprovalsWorkflowApprovalsApproveRead structure.
type WorkflowApprovalsWorkflowApprovalsApproveReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkflowApprovalsWorkflowApprovalsApproveReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkflowApprovalsWorkflowApprovalsApproveReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkflowApprovalsWorkflowApprovalsApproveReadOK creates a WorkflowApprovalsWorkflowApprovalsApproveReadOK with default headers values
func NewWorkflowApprovalsWorkflowApprovalsApproveReadOK() *WorkflowApprovalsWorkflowApprovalsApproveReadOK {
	return &WorkflowApprovalsWorkflowApprovalsApproveReadOK{}
}

/*WorkflowApprovalsWorkflowApprovalsApproveReadOK handles this case with default header values.

OK
*/
type WorkflowApprovalsWorkflowApprovalsApproveReadOK struct {
}

func (o *WorkflowApprovalsWorkflowApprovalsApproveReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/workflow_approvals/{id}/approve/][%d] workflowApprovalsWorkflowApprovalsApproveReadOK ", 200)
}

func (o *WorkflowApprovalsWorkflowApprovalsApproveReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
