// Code generated by go-swagger; DO NOT EDIT.

package job_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobEventsJobEventsReadReader is a Reader for the JobEventsJobEventsRead structure.
type JobEventsJobEventsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobEventsJobEventsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobEventsJobEventsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJobEventsJobEventsReadOK creates a JobEventsJobEventsReadOK with default headers values
func NewJobEventsJobEventsReadOK() *JobEventsJobEventsReadOK {
	return &JobEventsJobEventsReadOK{}
}

/*JobEventsJobEventsReadOK handles this case with default header values.

OK
*/
type JobEventsJobEventsReadOK struct {
}

func (o *JobEventsJobEventsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/job_events/{id}/][%d] jobEventsJobEventsReadOK ", 200)
}

func (o *JobEventsJobEventsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
